# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quinn/Documents/git/ethrin/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quinn/Documents/git/ethrin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Documents/git/ethrin/CMakeFiles /home/quinn/Documents/git/ethrin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Documents/git/ethrin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ethrin.bin

# Build rule for target.
ethrin.bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ethrin.bin
.PHONY : ethrin.bin

# fast build rule for target.
ethrin.bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/build
.PHONY : ethrin.bin/fast

boot/gdt.o: boot/gdt.asm.o
.PHONY : boot/gdt.o

# target to build an object file
boot/gdt.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/boot/gdt.asm.o
.PHONY : boot/gdt.asm.o

boot/idt.o: boot/idt.asm.o
.PHONY : boot/idt.o

# target to build an object file
boot/idt.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/boot/idt.asm.o
.PHONY : boot/idt.asm.o

boot/interrupt.o: boot/interrupt.asm.o
.PHONY : boot/interrupt.o

# target to build an object file
boot/interrupt.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/boot/interrupt.asm.o
.PHONY : boot/interrupt.asm.o

calloc/calloc.o: calloc/calloc.cpp.o
.PHONY : calloc/calloc.o

# target to build an object file
calloc/calloc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/calloc/calloc.cpp.o
.PHONY : calloc/calloc.cpp.o

calloc/calloc.i: calloc/calloc.cpp.i
.PHONY : calloc/calloc.i

# target to preprocess a source file
calloc/calloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/calloc/calloc.cpp.i
.PHONY : calloc/calloc.cpp.i

calloc/calloc.s: calloc/calloc.cpp.s
.PHONY : calloc/calloc.s

# target to generate assembly for a file
calloc/calloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/calloc/calloc.cpp.s
.PHONY : calloc/calloc.cpp.s

devices/pci.o: devices/pci.cpp.o
.PHONY : devices/pci.o

# target to build an object file
devices/pci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci.cpp.o
.PHONY : devices/pci.cpp.o

devices/pci.i: devices/pci.cpp.i
.PHONY : devices/pci.i

# target to preprocess a source file
devices/pci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci.cpp.i
.PHONY : devices/pci.cpp.i

devices/pci.s: devices/pci.cpp.s
.PHONY : devices/pci.s

# target to generate assembly for a file
devices/pci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci.cpp.s
.PHONY : devices/pci.cpp.s

devices/pci_common.o: devices/pci_common.cpp.o
.PHONY : devices/pci_common.o

# target to build an object file
devices/pci_common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci_common.cpp.o
.PHONY : devices/pci_common.cpp.o

devices/pci_common.i: devices/pci_common.cpp.i
.PHONY : devices/pci_common.i

# target to preprocess a source file
devices/pci_common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci_common.cpp.i
.PHONY : devices/pci_common.cpp.i

devices/pci_common.s: devices/pci_common.cpp.s
.PHONY : devices/pci_common.s

# target to generate assembly for a file
devices/pci_common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci_common.cpp.s
.PHONY : devices/pci_common.cpp.s

devices/pci_default.o: devices/pci_default.cpp.o
.PHONY : devices/pci_default.o

# target to build an object file
devices/pci_default.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci_default.cpp.o
.PHONY : devices/pci_default.cpp.o

devices/pci_default.i: devices/pci_default.cpp.i
.PHONY : devices/pci_default.i

# target to preprocess a source file
devices/pci_default.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci_default.cpp.i
.PHONY : devices/pci_default.cpp.i

devices/pci_default.s: devices/pci_default.cpp.s
.PHONY : devices/pci_default.s

# target to generate assembly for a file
devices/pci_default.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/devices/pci_default.cpp.s
.PHONY : devices/pci_default.cpp.s

fonts/psf.o: fonts/psf.cpp.o
.PHONY : fonts/psf.o

# target to build an object file
fonts/psf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/fonts/psf.cpp.o
.PHONY : fonts/psf.cpp.o

fonts/psf.i: fonts/psf.cpp.i
.PHONY : fonts/psf.i

# target to preprocess a source file
fonts/psf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/fonts/psf.cpp.i
.PHONY : fonts/psf.cpp.i

fonts/psf.s: fonts/psf.cpp.s
.PHONY : fonts/psf.s

# target to generate assembly for a file
fonts/psf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/fonts/psf.cpp.s
.PHONY : fonts/psf.cpp.s

graphics/graphics.o: graphics/graphics.cpp.o
.PHONY : graphics/graphics.o

# target to build an object file
graphics/graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/graphics/graphics.cpp.o
.PHONY : graphics/graphics.cpp.o

graphics/graphics.i: graphics/graphics.cpp.i
.PHONY : graphics/graphics.i

# target to preprocess a source file
graphics/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/graphics/graphics.cpp.i
.PHONY : graphics/graphics.cpp.i

graphics/graphics.s: graphics/graphics.cpp.s
.PHONY : graphics/graphics.s

# target to generate assembly for a file
graphics/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/graphics/graphics.cpp.s
.PHONY : graphics/graphics.cpp.s

i686-pc-none-elf/boot/boot.o: i686-pc-none-elf/boot/boot.asm.o
.PHONY : i686-pc-none-elf/boot/boot.o

# target to build an object file
i686-pc-none-elf/boot/boot.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/i686-pc-none-elf/boot/boot.asm.o
.PHONY : i686-pc-none-elf/boot/boot.asm.o

i686-pc-none-elf/i686.o: i686-pc-none-elf/i686.cpp.o
.PHONY : i686-pc-none-elf/i686.o

# target to build an object file
i686-pc-none-elf/i686.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/i686-pc-none-elf/i686.cpp.o
.PHONY : i686-pc-none-elf/i686.cpp.o

i686-pc-none-elf/i686.i: i686-pc-none-elf/i686.cpp.i
.PHONY : i686-pc-none-elf/i686.i

# target to preprocess a source file
i686-pc-none-elf/i686.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/i686-pc-none-elf/i686.cpp.i
.PHONY : i686-pc-none-elf/i686.cpp.i

i686-pc-none-elf/i686.s: i686-pc-none-elf/i686.cpp.s
.PHONY : i686-pc-none-elf/i686.s

# target to generate assembly for a file
i686-pc-none-elf/i686.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/i686-pc-none-elf/i686.cpp.s
.PHONY : i686-pc-none-elf/i686.cpp.s

malloc/malloc.o: malloc/malloc.cpp.o
.PHONY : malloc/malloc.o

# target to build an object file
malloc/malloc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/malloc/malloc.cpp.o
.PHONY : malloc/malloc.cpp.o

malloc/malloc.i: malloc/malloc.cpp.i
.PHONY : malloc/malloc.i

# target to preprocess a source file
malloc/malloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/malloc/malloc.cpp.i
.PHONY : malloc/malloc.cpp.i

malloc/malloc.s: malloc/malloc.cpp.s
.PHONY : malloc/malloc.s

# target to generate assembly for a file
malloc/malloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/malloc/malloc.cpp.s
.PHONY : malloc/malloc.cpp.s

math.o: math.cpp.o
.PHONY : math.o

# target to build an object file
math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/math.cpp.o
.PHONY : math.cpp.o

math.i: math.cpp.i
.PHONY : math.i

# target to preprocess a source file
math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/math.cpp.i
.PHONY : math.cpp.i

math.s: math.cpp.s
.PHONY : math.s

# target to generate assembly for a file
math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/math.cpp.s
.PHONY : math.cpp.s

memcpy/memcpy.o: memcpy/memcpy.cpp.o
.PHONY : memcpy/memcpy.o

# target to build an object file
memcpy/memcpy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/memcpy/memcpy.cpp.o
.PHONY : memcpy/memcpy.cpp.o

memcpy/memcpy.i: memcpy/memcpy.cpp.i
.PHONY : memcpy/memcpy.i

# target to preprocess a source file
memcpy/memcpy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/memcpy/memcpy.cpp.i
.PHONY : memcpy/memcpy.cpp.i

memcpy/memcpy.s: memcpy/memcpy.cpp.s
.PHONY : memcpy/memcpy.s

# target to generate assembly for a file
memcpy/memcpy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/memcpy/memcpy.cpp.s
.PHONY : memcpy/memcpy.cpp.s

memset/memset.o: memset/memset.cpp.o
.PHONY : memset/memset.o

# target to build an object file
memset/memset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/memset/memset.cpp.o
.PHONY : memset/memset.cpp.o

memset/memset.i: memset/memset.cpp.i
.PHONY : memset/memset.i

# target to preprocess a source file
memset/memset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/memset/memset.cpp.i
.PHONY : memset/memset.cpp.i

memset/memset.s: memset/memset.cpp.s
.PHONY : memset/memset.s

# target to generate assembly for a file
memset/memset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/memset/memset.cpp.s
.PHONY : memset/memset.cpp.s

minikernel/minikernel.o: minikernel/minikernel.cpp.o
.PHONY : minikernel/minikernel.o

# target to build an object file
minikernel/minikernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/minikernel/minikernel.cpp.o
.PHONY : minikernel/minikernel.cpp.o

minikernel/minikernel.i: minikernel/minikernel.cpp.i
.PHONY : minikernel/minikernel.i

# target to preprocess a source file
minikernel/minikernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/minikernel/minikernel.cpp.i
.PHONY : minikernel/minikernel.cpp.i

minikernel/minikernel.s: minikernel/minikernel.cpp.s
.PHONY : minikernel/minikernel.s

# target to generate assembly for a file
minikernel/minikernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/minikernel/minikernel.cpp.s
.PHONY : minikernel/minikernel.cpp.s

notify/notify.o: notify/notify.cpp.o
.PHONY : notify/notify.o

# target to build an object file
notify/notify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/notify/notify.cpp.o
.PHONY : notify/notify.cpp.o

notify/notify.i: notify/notify.cpp.i
.PHONY : notify/notify.i

# target to preprocess a source file
notify/notify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/notify/notify.cpp.i
.PHONY : notify/notify.cpp.i

notify/notify.s: notify/notify.cpp.s
.PHONY : notify/notify.s

# target to generate assembly for a file
notify/notify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/notify/notify.cpp.s
.PHONY : notify/notify.cpp.s

stdio.o: stdio.cpp.o
.PHONY : stdio.o

# target to build an object file
stdio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/stdio.cpp.o
.PHONY : stdio.cpp.o

stdio.i: stdio.cpp.i
.PHONY : stdio.i

# target to preprocess a source file
stdio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/stdio.cpp.i
.PHONY : stdio.cpp.i

stdio.s: stdio.cpp.s
.PHONY : stdio.s

# target to generate assembly for a file
stdio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/stdio.cpp.s
.PHONY : stdio.cpp.s

string.o: string.cpp.o
.PHONY : string.o

# target to build an object file
string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/string.cpp.o
.PHONY : string.cpp.o

string.i: string.cpp.i
.PHONY : string.i

# target to preprocess a source file
string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/string.cpp.i
.PHONY : string.cpp.i

string.s: string.cpp.s
.PHONY : string.s

# target to generate assembly for a file
string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/string.cpp.s
.PHONY : string.cpp.s

sys/portio.o: sys/portio.c.o
.PHONY : sys/portio.o

# target to build an object file
sys/portio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/sys/portio.c.o
.PHONY : sys/portio.c.o

sys/portio.i: sys/portio.c.i
.PHONY : sys/portio.i

# target to preprocess a source file
sys/portio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/sys/portio.c.i
.PHONY : sys/portio.c.i

sys/portio.s: sys/portio.c.s
.PHONY : sys/portio.s

# target to generate assembly for a file
sys/portio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/sys/portio.c.s
.PHONY : sys/portio.c.s

tables/gdt.o: tables/gdt.cpp.o
.PHONY : tables/gdt.o

# target to build an object file
tables/gdt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/gdt.cpp.o
.PHONY : tables/gdt.cpp.o

tables/gdt.i: tables/gdt.cpp.i
.PHONY : tables/gdt.i

# target to preprocess a source file
tables/gdt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/gdt.cpp.i
.PHONY : tables/gdt.cpp.i

tables/gdt.s: tables/gdt.cpp.s
.PHONY : tables/gdt.s

# target to generate assembly for a file
tables/gdt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/gdt.cpp.s
.PHONY : tables/gdt.cpp.s

tables/idt.o: tables/idt.cpp.o
.PHONY : tables/idt.o

# target to build an object file
tables/idt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/idt.cpp.o
.PHONY : tables/idt.cpp.o

tables/idt.i: tables/idt.cpp.i
.PHONY : tables/idt.i

# target to preprocess a source file
tables/idt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/idt.cpp.i
.PHONY : tables/idt.cpp.i

tables/idt.s: tables/idt.cpp.s
.PHONY : tables/idt.s

# target to generate assembly for a file
tables/idt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/idt.cpp.s
.PHONY : tables/idt.cpp.s

tables/isr.o: tables/isr.cpp.o
.PHONY : tables/isr.o

# target to build an object file
tables/isr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/isr.cpp.o
.PHONY : tables/isr.cpp.o

tables/isr.i: tables/isr.cpp.i
.PHONY : tables/isr.i

# target to preprocess a source file
tables/isr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/isr.cpp.i
.PHONY : tables/isr.cpp.i

tables/isr.s: tables/isr.cpp.s
.PHONY : tables/isr.s

# target to generate assembly for a file
tables/isr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/tables/isr.cpp.s
.PHONY : tables/isr.cpp.s

vesa/vesa.o: vesa/vesa.cpp.o
.PHONY : vesa/vesa.o

# target to build an object file
vesa/vesa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vesa/vesa.cpp.o
.PHONY : vesa/vesa.cpp.o

vesa/vesa.i: vesa/vesa.cpp.i
.PHONY : vesa/vesa.i

# target to preprocess a source file
vesa/vesa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vesa/vesa.cpp.i
.PHONY : vesa/vesa.cpp.i

vesa/vesa.s: vesa/vesa.cpp.s
.PHONY : vesa/vesa.s

# target to generate assembly for a file
vesa/vesa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vesa/vesa.cpp.s
.PHONY : vesa/vesa.cpp.s

vfs/dev.o: vfs/dev.cpp.o
.PHONY : vfs/dev.o

# target to build an object file
vfs/dev.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vfs/dev.cpp.o
.PHONY : vfs/dev.cpp.o

vfs/dev.i: vfs/dev.cpp.i
.PHONY : vfs/dev.i

# target to preprocess a source file
vfs/dev.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vfs/dev.cpp.i
.PHONY : vfs/dev.cpp.i

vfs/dev.s: vfs/dev.cpp.s
.PHONY : vfs/dev.s

# target to generate assembly for a file
vfs/dev.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vfs/dev.cpp.s
.PHONY : vfs/dev.cpp.s

vfs/vfs.o: vfs/vfs.cpp.o
.PHONY : vfs/vfs.o

# target to build an object file
vfs/vfs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vfs/vfs.cpp.o
.PHONY : vfs/vfs.cpp.o

vfs/vfs.i: vfs/vfs.cpp.i
.PHONY : vfs/vfs.i

# target to preprocess a source file
vfs/vfs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vfs/vfs.cpp.i
.PHONY : vfs/vfs.cpp.i

vfs/vfs.s: vfs/vfs.cpp.s
.PHONY : vfs/vfs.s

# target to generate assembly for a file
vfs/vfs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ethrin.bin.dir/build.make CMakeFiles/ethrin.bin.dir/vfs/vfs.cpp.s
.PHONY : vfs/vfs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ethrin.bin"
	@echo "... boot/gdt.o"
	@echo "... boot/idt.o"
	@echo "... boot/interrupt.o"
	@echo "... calloc/calloc.o"
	@echo "... calloc/calloc.i"
	@echo "... calloc/calloc.s"
	@echo "... devices/pci.o"
	@echo "... devices/pci.i"
	@echo "... devices/pci.s"
	@echo "... devices/pci_common.o"
	@echo "... devices/pci_common.i"
	@echo "... devices/pci_common.s"
	@echo "... devices/pci_default.o"
	@echo "... devices/pci_default.i"
	@echo "... devices/pci_default.s"
	@echo "... fonts/psf.o"
	@echo "... fonts/psf.i"
	@echo "... fonts/psf.s"
	@echo "... graphics/graphics.o"
	@echo "... graphics/graphics.i"
	@echo "... graphics/graphics.s"
	@echo "... i686-pc-none-elf/boot/boot.o"
	@echo "... i686-pc-none-elf/i686.o"
	@echo "... i686-pc-none-elf/i686.i"
	@echo "... i686-pc-none-elf/i686.s"
	@echo "... malloc/malloc.o"
	@echo "... malloc/malloc.i"
	@echo "... malloc/malloc.s"
	@echo "... math.o"
	@echo "... math.i"
	@echo "... math.s"
	@echo "... memcpy/memcpy.o"
	@echo "... memcpy/memcpy.i"
	@echo "... memcpy/memcpy.s"
	@echo "... memset/memset.o"
	@echo "... memset/memset.i"
	@echo "... memset/memset.s"
	@echo "... minikernel/minikernel.o"
	@echo "... minikernel/minikernel.i"
	@echo "... minikernel/minikernel.s"
	@echo "... notify/notify.o"
	@echo "... notify/notify.i"
	@echo "... notify/notify.s"
	@echo "... stdio.o"
	@echo "... stdio.i"
	@echo "... stdio.s"
	@echo "... string.o"
	@echo "... string.i"
	@echo "... string.s"
	@echo "... sys/portio.o"
	@echo "... sys/portio.i"
	@echo "... sys/portio.s"
	@echo "... tables/gdt.o"
	@echo "... tables/gdt.i"
	@echo "... tables/gdt.s"
	@echo "... tables/idt.o"
	@echo "... tables/idt.i"
	@echo "... tables/idt.s"
	@echo "... tables/isr.o"
	@echo "... tables/isr.i"
	@echo "... tables/isr.s"
	@echo "... vesa/vesa.o"
	@echo "... vesa/vesa.i"
	@echo "... vesa/vesa.s"
	@echo "... vfs/dev.o"
	@echo "... vfs/dev.i"
	@echo "... vfs/dev.s"
	@echo "... vfs/vfs.o"
	@echo "... vfs/vfs.i"
	@echo "... vfs/vfs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

